version: "3.5"
services:
  interceptor:
    container_name: interceptor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/app
    environment:
      APP_PORT: "80"
      API_DELAY_RESPONSE: "1000"
    networks:
        - krg.io
    ports:
    - 8009:80
networks:
  krg.io:
    external: true
